spring:
  application:
    name: genealogie
  datasource:
    url: jdbc:h2:file:./data/genealogie
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8121

hibernate:
  show_sql: true