spring:
  datasource:
    # When running the app on the host and MySQL in Podman with -p 3306:3306, use localhost
    # If you run the app in a container, override with SPRING_DATASOURCE_URL and point to the right host
    url: jdbc:mysql://localhost:3306/genealogie?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: genealogie
    password: genealogie
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:/db/migration/mysql

server:
  port: 8121

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"

# How to run with Podman MySQL (example):
# podman run --name mysql-genealogie -e MYSQL_ROOT_PASSWORD=rootpw -e MYSQL_DATABASE=genealogie -e MYSQL_USER=genealogie -e MYSQL_PASSWORD=genealogie -p 3306:3306 -d docker.io/library/mysql:8.0
# Start the app with profile:
#   java -jar infrastructuur/build/libs/genealogie-server-*.jar --spring.profiles.active=mysql
