CREATE TABLE genealogisch_driekhoekje
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    kind_id   BIGINT,
    moeder_id BIGINT,
    vader_id  BIGINT,
    CONSTRAINT pk_genealogisch_driekhoekje PRIMARY KEY (id)
);

CREATE TABLE huwelijk
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    persoon_1_id  BIGINT,
    persoon_2_id  BIGINT,
    gehuwd_op     date,
    gescheiden_op date,
    gehuwd_te     VARCHAR(255),
    CONSTRAINT pk_huwelijk PRIMARY KEY (id)
);

CREATE TABLE info_type
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    omschrijving VARCHAR(255),
    CONSTRAINT pk_info_type PRIMARY KEY (id)
);

CREATE TABLE natuurlijk_persoon
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    naam         VARCHAR(255),
    voornaam     VARCHAR(255),
    geboren_op   date,
    geboren_te   VARCHAR(255),
    overleden_op date,
    overleden_te VARCHAR(255),
    CONSTRAINT pk_natuurlijk_persoon PRIMARY KEY (id)
);

CREATE TABLE natuurlijk_persoon_info
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    persoon_id    BIGINT,
    kan_lezen     BOOLEAN,
    kan_schrijven BOOLEAN,
    kan_rekenen   BOOLEAN,
    CONSTRAINT pk_natuurlijk_persoon_info PRIMARY KEY (id)
);

CREATE TABLE onderzoeksinfo
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    persoon_id         BIGINT,
    info_type_id       BIGINT,
    link_naar_document VARCHAR(255),
    link_naar_bron     VARCHAR(255),
    extra_info         VARCHAR(255),
    CONSTRAINT pk_onderzoeksinfo PRIMARY KEY (id)
);

ALTER TABLE natuurlijk_persoon_info
    ADD CONSTRAINT uc_natuurlijk_persoon_info_persoon UNIQUE (persoon_id);

ALTER TABLE genealogisch_driekhoekje
    ADD CONSTRAINT FK_GENEALOGISCH_DRIEKHOEKJE_ON_KIND FOREIGN KEY (kind_id) REFERENCES natuurlijk_persoon (id);

ALTER TABLE genealogisch_driekhoekje
    ADD CONSTRAINT FK_GENEALOGISCH_DRIEKHOEKJE_ON_MOEDER FOREIGN KEY (moeder_id) REFERENCES natuurlijk_persoon (id);

ALTER TABLE genealogisch_driekhoekje
    ADD CONSTRAINT FK_GENEALOGISCH_DRIEKHOEKJE_ON_VADER FOREIGN KEY (vader_id) REFERENCES natuurlijk_persoon (id);

ALTER TABLE huwelijk
    ADD CONSTRAINT FK_HUWELIJK_ON_PERSOON_1 FOREIGN KEY (persoon_1_id) REFERENCES natuurlijk_persoon (id);

ALTER TABLE huwelijk
    ADD CONSTRAINT FK_HUWELIJK_ON_PERSOON_2 FOREIGN KEY (persoon_2_id) REFERENCES natuurlijk_persoon (id);

ALTER TABLE natuurlijk_persoon_info
    ADD CONSTRAINT FK_NATUURLIJK_PERSOON_INFO_ON_PERSOON FOREIGN KEY (persoon_id) REFERENCES natuurlijk_persoon (id);

ALTER TABLE onderzoeksinfo
    ADD CONSTRAINT FK_ONDERZOEKSINFO_ON_INFO_TYPE FOREIGN KEY (info_type_id) REFERENCES info_type (id);

ALTER TABLE onderzoeksinfo
    ADD CONSTRAINT FK_ONDERZOEKSINFO_ON_PERSOON FOREIGN KEY (persoon_id) REFERENCES natuurlijk_persoon (id);