CREATE TABLE beroep
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    persoon_id BIGINT,
    beroep     VARCHAR(255),
    CONSTRAINT pk_beroep PRIMARY KEY (id)
);

CREATE TABLE document
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type_id BIGINT,
    path             VARCHAR(255),
    transcript       VARCHAR(255),
    persoon_id       BIGINT,
    relatie_id       BIGINT,
    CONSTRAINT pk_document PRIMARY KEY (id)
);

CREATE TABLE document_type
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    omschrijving VARCHAR(255),
    code         VARCHAR(255),
    CONSTRAINT pk_document_type PRIMARY KEY (id)
);

CREATE TABLE gebruiker
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    voornaam      VARCHAR(255)                            NOT NULL,
    naam          VARCHAR(255)                            NOT NULL,
    email         VARCHAR(100)                            NOT NULL,
    wachtwoord    VARCHAR(255)                            NOT NULL,
    aangemaakt_op date,
    gewijzigd_op  date,
    CONSTRAINT pk_gebruiker PRIMARY KEY (id)
);

CREATE TABLE gebruiker_machtiging
(
    gebruiker_id  BIGINT NOT NULL,
    machtiging_id BIGINT NOT NULL
);

CREATE TABLE genealogisch_driekhoekje
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    kind_id    BIGINT,
    ouder_1_id BIGINT,
    ouder_2_id BIGINT,
    CONSTRAINT pk_genealogisch_driekhoekje PRIMARY KEY (id)
);

CREATE TABLE info_type
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    omschrijving VARCHAR(255),
    CONSTRAINT pk_info_type PRIMARY KEY (id)
);

CREATE TABLE machtigingen
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    machtiging VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_machtigingen PRIMARY KEY (id)
);

CREATE TABLE natuurlijk_persoon
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    naam         VARCHAR(255),
    voornaam     VARCHAR(255),
    geboren_op   date,
    geboren_te   VARCHAR(255),
    overleden_op date,
    overleden_te VARCHAR(255),
    geslacht     VARCHAR(255),
    CONSTRAINT pk_natuurlijk_persoon PRIMARY KEY (id)
);

CREATE TABLE natuurlijk_persoon_info
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    persoon_id    BIGINT,
    kan_lezen     BOOLEAN,
    kan_schrijven BOOLEAN,
    kan_rekenen   BOOLEAN,
    CONSTRAINT pk_natuurlijk_persoon_info PRIMARY KEY (id)
);

CREATE TABLE onderzoeksinfo
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    persoon_id         BIGINT,
    info_type_id       BIGINT,
    link_naar_document VARCHAR(255),
    link_naar_bron     VARCHAR(255),
    extra_info         VARCHAR(255),
    CONSTRAINT pk_onderzoeksinfo PRIMARY KEY (id)
);

CREATE TABLE relatie
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    persoon_1_id  BIGINT,
    persoon_2_id  BIGINT,
    gehuwd_op     date,
    gescheiden_op date,
    gehuwd_te     VARCHAR(255),
    uit_elkaar    BOOLEAN,
    CONSTRAINT pk_relatie PRIMARY KEY (id)
);

ALTER TABLE gebruiker
    ADD CONSTRAINT uc_gebruiker_email UNIQUE (email);

ALTER TABLE natuurlijk_persoon_info
    ADD CONSTRAINT uc_natuurlijk_persoon_info_persoon UNIQUE (persoon_id);

ALTER TABLE beroep
    ADD CONSTRAINT FK_BEROEP_ON_PERSOON FOREIGN KEY (persoon_id) REFERENCES natuurlijk_persoon (id);

ALTER TABLE document
    ADD CONSTRAINT FK_DOCUMENT_ON_DOCUMENT_TYPE FOREIGN KEY (document_type_id) REFERENCES document_type (id);

ALTER TABLE document
    ADD CONSTRAINT FK_DOCUMENT_ON_PERSOON FOREIGN KEY (persoon_id) REFERENCES natuurlijk_persoon (id);

ALTER TABLE document
    ADD CONSTRAINT FK_DOCUMENT_ON_RELATIE FOREIGN KEY (relatie_id) REFERENCES relatie (id);

ALTER TABLE genealogisch_driekhoekje
    ADD CONSTRAINT FK_GENEALOGISCH_DRIEKHOEKJE_ON_KIND FOREIGN KEY (kind_id) REFERENCES natuurlijk_persoon (id);

ALTER TABLE genealogisch_driekhoekje
    ADD CONSTRAINT FK_GENEALOGISCH_DRIEKHOEKJE_ON_OUDER_1 FOREIGN KEY (ouder_1_id) REFERENCES natuurlijk_persoon (id);

ALTER TABLE genealogisch_driekhoekje
    ADD CONSTRAINT FK_GENEALOGISCH_DRIEKHOEKJE_ON_OUDER_2 FOREIGN KEY (ouder_2_id) REFERENCES natuurlijk_persoon (id);

ALTER TABLE natuurlijk_persoon_info
    ADD CONSTRAINT FK_NATUURLIJK_PERSOON_INFO_ON_PERSOON FOREIGN KEY (persoon_id) REFERENCES natuurlijk_persoon (id);

ALTER TABLE onderzoeksinfo
    ADD CONSTRAINT FK_ONDERZOEKSINFO_ON_INFO_TYPE FOREIGN KEY (info_type_id) REFERENCES info_type (id);

ALTER TABLE onderzoeksinfo
    ADD CONSTRAINT FK_ONDERZOEKSINFO_ON_PERSOON FOREIGN KEY (persoon_id) REFERENCES natuurlijk_persoon (id);

ALTER TABLE relatie
    ADD CONSTRAINT FK_RELATIE_ON_PERSOON_1 FOREIGN KEY (persoon_1_id) REFERENCES natuurlijk_persoon (id);

ALTER TABLE relatie
    ADD CONSTRAINT FK_RELATIE_ON_PERSOON_2 FOREIGN KEY (persoon_2_id) REFERENCES natuurlijk_persoon (id);

ALTER TABLE gebruiker_machtiging
    ADD CONSTRAINT fk_gebmac_on_gebruiker FOREIGN KEY (gebruiker_id) REFERENCES gebruiker (id);

ALTER TABLE gebruiker_machtiging
    ADD CONSTRAINT fk_gebmac_on_machtiging FOREIGN KEY (machtiging_id) REFERENCES machtigingen (id);