CREATE TABLE beroep
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    persoon_id BIGINT,
    beroep     VARCHAR(255),
    CONSTRAINT pk_beroep PRIMARY KEY (id)
);

ALTER TABLE beroep
    ADD CONSTRAINT FK_BEROEP_ON_PERSOON FOREIGN KEY (persoon_id) REFERENCES natuurlijk_persoon (id);