package be.genealogie.controller.page;

public enum WebPagina {
    LOGIN, REGISTER, ZOEKEN, NIEUW_PERSOON, NATUURLIJK_PERSOON_FICHE, NATUURLIJK_PERSOON_FICHE_RELATIE_TOEVOEGEN,
    NATUURLIJK_PERSOON_FICHE_PERSOON_AAN_RELATIE_TOEVOEGEN,
    NATUURLIJK_PERSOON_FICHE_OUDERS_TOEVOEGEN, NATUURLIJK_PERSOON_FICHE_EDITEER
}
